# docker-compose -f .\docker-compose.yaml up
version: '3'
services:
  max-nextjs: # container name
    image: max-nextjs-app:latest
    ports:
      - 3000:3000
    # Taken from https://console.cloud.google.com/apis/
    environment:
      - YOUTUBE_API_KEY=
      - YOUTUBE_CHANNEL_ID=